### ISSUE TITLE
Play Store Checklist

### ISSUE THREAD

**Issue by rc-young** [willowtreeapps/vocable-android#216]
- [x] Localized "What's new..."
- [x] Localized "Description - Italian"
- [ ] Inform WT Marketing
- [ ] Localized screenshots 
- [x] App Submission 

https://docs.google.com/document/d/1vjtaun5qHm1KUaCQq8uMDE0PRuPh-SElQLC9bB3CIkA/edit
